# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

update_counts_noreg_inner <- function(self, i_interval) {
    invisible(.Call(`_dpmpf_update_counts_noreg_inner`, self, i_interval))
}

update_counts_withreg_inner <- function(self, i_interval) {
    invisible(.Call(`_dpmpf_update_counts_withreg_inner`, self, i_interval))
}

dpoibin1 <- function(x, size, prob, use_log) {
    .Call(`_dpmpf_dpoibin1`, x, size, prob, use_log)
}

rpoibin1 <- function(size, prob) {
    .Call(`_dpmpf_rpoibin1`, size, prob)
}

rpoistr1 <- function(lambda, lower) {
    .Call(`_dpmpf_rpoistr1`, lambda, lower)
}

rpoistr <- function(n, lambda, lower) {
    .Call(`_dpmpf_rpoistr`, n, lambda, lower)
}

dpoistr <- function(x, lambda, lower, use_log) {
    .Call(`_dpmpf_dpoistr`, x, lambda, lower, use_log)
}

pnchisq_approx <- function(q, df, ncp, lower, use_log) {
    .Call(`_dpmpf_pnchisq_approx`, q, df, ncp, lower, use_log)
}

pnchisq_switch <- function(q, df, ncp, lower, use_log) {
    .Call(`_dpmpf_pnchisq_switch`, q, df, ncp, lower, use_log)
}

pskel1 <- function(q, mu1, mu2, lower_tail, log_p) {
    .Call(`_dpmpf_pskel1`, q, mu1, mu2, lower_tail, log_p)
}

pskel <- function(q, mu1, mu2, lower_tail, log_p) {
    .Call(`_dpmpf_pskel`, q, mu1, mu2, lower_tail, log_p)
}

qskel1 <- function(p, mu1, mu2) {
    .Call(`_dpmpf_qskel1`, p, mu1, mu2)
}

rskeltr1 <- function(mu1, mu2, lower) {
    .Call(`_dpmpf_rskeltr1`, mu1, mu2, lower)
}

rskeltr <- function(n, mu1, mu2, lower) {
    .Call(`_dpmpf_rskeltr`, n, mu1, mu2, lower)
}

dskel1 <- function(x, mu1, mu2, use_log) {
    .Call(`_dpmpf_dskel1`, x, mu1, mu2, use_log)
}

dskeltr1 <- function(x, mu1, mu2, lower, use_log) {
    .Call(`_dpmpf_dskeltr1`, x, mu1, mu2, lower, use_log)
}

dskeltr <- function(x, mu1, mu2, lower, use_log) {
    .Call(`_dpmpf_dskeltr`, x, mu1, mu2, lower, use_log)
}

log_sum_exp_2 <- function(x, y) {
    .Call(`_dpmpf_log_sum_exp_2`, x, y)
}

